### ISSUE TITLE
rights management

### ISSUE THREAD

**Issue by Dancbeunny98** [J-Tanzanite/Little-Anti-Cheat#41] opened 2020-10-03 18:45 UTC
If a person has certain flags, then he is completely ignored by the anti-cheat or partially. Can you do this? Tell me how to do it.

**Comment by Dancbeunny98** [comment] 2020-10-03 23:40
PLS. PM ME FOR help. Discord: Dancebunny98#3658

**Comment by Dancbeunny98** [comment] 2020-10-04 14:00
#42

**Comment by J-Tanzanite** [comment] 2020-10-04 19:13
I'm not entirely sure what your problem is, but it sounds like you are asking about a similar issue someone else had here: https://forums.alliedmods.net/showthread.php?t=321480&page=19

Lilac will send a forward when a player has been detected of using cheats, and you can tell Lilac to ignore the cheat detection by returning Plugin_Handled or Plugin_Stop for the forward `lilac_allow_cheat_detection(int client, int cheat)`.

This is pseudocode, don't expect this to work, but should at least get you in the right direction.
``` c
public Action lilac_allow_cheat_detection(int client, int cheat)
{
	// Block the cheat detection if the client has the flag ADMFLAG_CUSTOM1.
	if (CheckCommandAccess(client, "", ADMFLAG_CUSTOM1) || (GetUserFlagBits(client) & ADMFLAG_CUSTOM1)) {
		return Plugin_Handled;
	}

	return Plugin_Continue;
}
```

# NOTE!
I've never used `GetUserFlagBits()` or `CheckCommandAccess()` before, so I don't know if this is the correct way of doing it!

As far as I know tho, `GetUserFlagBits()` shouldn't be used, and you should use `CheckCommandAccess()` to check if a player has a certain admin flag, which can be found in "addons/sourcemod/configs/admin_levels.cfg" and set in "addons/sourcemod/configs/admins_simple.ini".

For a full list of Admin flags, look here: https://sm.alliedmods.net/new-api/admin/__raw or https://wiki.alliedmods.net/Checking_Admin_Flags_(SourceMod_Scripting)



### AGAIN!
I haven't done this before, and I am not sure this is the problem you are having, but I hope this at least helps.

**Comment by Dancbeunny98** [comment] 2020-10-05 21:01
![image](https://user-images.githubusercontent.com/37336183/95131618-0b725400-0767-11eb-8065-5b426280d10c.png)

**Comment by J-Tanzanite** [comment] 2020-10-06 08:34
I checked out line 2149, and as your error suggests, line 2149 should be inside the function `lilac_log_setup_client()`.
However, in both the stable and development versions of Lilac, line 2149 isn't inside `lilac_log_setup_client()`

What version of Lilac are you having issues with? And did you or someone else do any modifications to it?

**Comment by Dancbeunny98** [comment] 2020-10-06 20:33
![image](https://user-images.githubusercontent.com/37336183/95257009-5904c480-082c-11eb-82c6-297b687dd97d.png)

**Comment by Dancbeunny98** [comment] 2020-10-06 20:33
MA installed!

**Comment by J-Tanzanite** [comment] 2020-10-07 07:30
`WARNING: Material-Admin was NOT included when compiled, banning through MA won't work!`
It says it right there, MA wasn't **included** when **compiled**.
You just need to put the `materialadmin.inc` in your `addons/sourcemod/scripting/include` folder and then compile Lilac for MA bans to work. :)

But just remember that for MA and SB++ to work, they must be included in the `addons/sourcemod/scripting/include` folder before you compile for Lilac to support MA and SB++.

The pre-compiled plugin comes with MA and SB++ support out of the box tho.

---

You didn't really answer my previous question, so I'm going to assume you're making your own changes to Lilac, which is fine :)

But if you ask about problems after having made your own changes and not showing those changes to me - then helping you becomes near impossible.

**Comment by Dancbeunny98** [comment] 2020-10-07 17:43
> I checked out line 2149, and as your error suggests, line 2149 should be inside the function `lilac_log_setup_client()`.
> However, in both the stable and development versions of Lilac, line 2149 isn't inside `lilac_log_setup_client()`
> 
> What version of Lilac are you having issues with? And did you or someone else do any modifications to it?

I've already fixed it. I want to ask you how can I change the reason? I want to strip the output of the plugin version. This is neither me nor the person who received the lock.

**Comment by Dancbeunny98** [comment] 2020-10-07 17:45
> `WARNING: Material-Admin was NOT included when compiled, banning through MA won't work!`
> It says it right there, MA wasn't **included** when **compiled**.
> You just need to put the `materialadmin.inc` in your `addons/sourcemod/scripting/include` folder and then compile Lilac for MA bans to work. :)
> 
> But just remember that for MA and SB++ to work, they must be included in the `addons/sourcemod/scripting/include` folder before you compile for Lilac to support MA and SB++.
> 
> The pre-compiled plugin comes with MA and SB++ support out of the box tho.
> 
> You didn't really answer my previous question, so I'm going to assume you're making your own changes to Lilac, which is fine :)
> 
> But if you ask about problems after having made your own changes and not showing those changes to me - then helping you becomes near impossible.

I am using [this](https://github.com/SB-MaterialAdmin/NewServer). There are several in one. And they were when I compiled the plugin.

**Comment by Dancbeunny98** [comment] 2020-10-07 17:47
> I'm not entirely sure what your problem is, but it sounds like you are asking about a similar issue someone else had here: https://forums.alliedmods.net/showthread.php?t=321480&page=19
> 
> Lilac will send a forward when a player has been detected of using cheats, and you can tell Lilac to ignore the cheat detection by returning Plugin_Handled or Plugin_Stop for the forward `lilac_allow_cheat_detection(int client, int cheat)`.
> 
> This is pseudocode, don't expect this to work, but should at least get you in the right direction.
> 
> ```c
> public Action lilac_allow_cheat_detection(int client, int cheat)
> {
> 	// Block the cheat detection if the client has the flag ADMFLAG_CUSTOM1.
> 	if (CheckCommandAccess(client, "", ADMFLAG_CUSTOM1) || (GetUserFlagBits(client) & ADMFLAG_CUSTOM1)) {
> 		return Plugin_Handled;
> 	}
> 
> 	return Plugin_Continue;
> }
> ```
> 
> # NOTE!
> I've never used `GetUserFlagBits()` or `CheckCommandAccess()` before, so I don't know if this is the correct way of doing it!
> 
> As far as I know tho, `GetUserFlagBits()` shouldn't be used, and you should use `CheckCommandAccess()` to check if a player has a certain admin flag, which can be found in "addons/sourcemod/configs/admin_levels.cfg" and set in "addons/sourcemod/configs/admins_simple.ini".
> 
> For a full list of Admin flags, look here: https://sm.alliedmods.net/new-api/admin/__raw or https://wiki.alliedmods.net/Checking_Admin_Flags_(SourceMod_Scripting)
> 
> ### AGAIN!
> I haven't done this before, and I am not sure this is the problem you are having, but I hope this at least helps.
I inserted this parameter here.
![image](https://user-images.githubusercontent.com/37336183/95368089-49de4f00-08de-11eb-8bcb-a230ea2d7e2c.png)

**Comment by Dancbeunny98** [comment] 2020-10-07 17:47
> > I'm not entirely sure what your problem is, but it sounds like you are asking about a similar issue someone else had here: https://forums.alliedmods.net/showthread.php?t=321480&page=19
> > Lilac will send a forward when a player has been detected of using cheats, and you can tell Lilac to ignore the cheat detection by returning Plugin_Handled or Plugin_Stop for the forward `lilac_allow_cheat_detection(int client, int cheat)`.
> > This is pseudocode, don't expect this to work, but should at least get you in the right direction.
> > ```c
> > public Action lilac_allow_cheat_detection(int client, int cheat)
> > {
> > 	// Block the cheat detection if the client has the flag ADMFLAG_CUSTOM1.
> > 	if (CheckCommandAccess(client, "", ADMFLAG_CUSTOM1) || (GetUserFlagBits(client) & ADMFLAG_CUSTOM1)) {
> > 		return Plugin_Handled;
> > 	}
> > 
> > 	return Plugin_Continue;
> > }
> > ```
> > 
> > 
> > # NOTE!
> > I've never used `GetUserFlagBits()` or `CheckCommandAccess()` before, so I don't know if this is the correct way of doing it!
> > As far as I know tho, `GetUserFlagBits()` shouldn't be used, and you should use `CheckCommandAccess()` to check if a player has a certain admin flag, which can be found in "addons/sourcemod/configs/admin_levels.cfg" and set in "addons/sourcemod/configs/admins_simple.ini".
> > For a full list of Admin flags, look here: https://sm.alliedmods.net/new-api/admin/__raw or https://wiki.alliedmods.net/Checking_Admin_Flags_(SourceMod_Scripting)
> > ### AGAIN!
> > I haven't done this before, and I am not sure this is the problem you are having, but I hope this at least helps.
> > I inserted this parameter here.
> > ![image](https://user-images.githubusercontent.com/37336183/95368089-49de4f00-08de-11eb-8bcb-a230ea2d7e2c.png)

ITS WORK)

**Comment by J-Tanzanite** [comment] 2020-10-11 11:52
"ITS WORK)"

... Guessing you made it work, and the issue is solved?

**Comment by Dancbeunny98** [comment] 2020-10-11 16:27
> "ITS WORK)"
> 
> ... Guessing you made it work, and the issue is solved?

I want to understand now. How to change this. But I think I'll figure it out. Thanks. The issue has been resolved.

![image](https://user-images.githubusercontent.com/37336183/95684088-c1babb00-0bf7-11eb-9a43-d4dde073c2ed.png)

**Comment by Dancbeunny98** [comment] 2020-10-11 16:36
And I still have no plugins SB \ MA

```
  20 "Material Admin" (0.7.9) by Material Admin Dev Team
```

**Comment by J-Tanzanite** [comment] 2020-10-22 10:01
### For future reference, in case anyone else finds this thread (Or I forget why I closed this)...
I'm closing this issue for the reasons mentioned in my comment here: https://github.com/J-Tanzanite/Little-Anti-Cheat/issues/45#issuecomment-712161550

**Closed by J-Tanzanite** 2020-10-22 10:01 UTC
