### ISSUE TITLE
False positive for aimlock.

### ISSUE THREAD

**Issue by Androidonator** [J-Tanzanite/Little-Anti-Cheat#73] opened 2021-03-23 18:53 UTC
I just got false positive banned on a server in tf2 on a orange x4 map with fast respawn and few teleports.
Why are the mention of fast respawns and teleport important is because i might have got false positive banned for supposed aimlock. I am 100% sure i am not cheating or running any software of any kind. I tried looking trough the code for possible solution. Also the server admin doesnt want to give me logs or anything. Now listen to me If i was cheating I woudlnt be going so far as asking the original plugin creator for help, but you are the only authority here that can sway the perma in my favor. I am a player whomst stands behind theirs good reputation as a legit player. I am beyond lawful I will do anything to prove my innocence.
If you can explain to me how exactly does the aimlock detection work because i couldnt work it out from the code myself that would be helpful too.
Here is link for the map i got banned on. 
https://drive.google.com/file/d/1MrQk-Ll7PCfrulMnwE-J4E2ZW67u2kD8/view?usp=sharing
Also I am not some aim god or anything so I dont understand it at all.
If there is any posibillity for false positive to happen confirmed by you it would give me a solid ground to ask server admins for logs.

**Comment by J-Tanzanite** [comment] 2021-03-24 10:01
For server owners / admins reading this: Hi, I'm the Author of Little Anti-Cheat, and I can confirm that there **might** have been a false positive ban of this player. Read below to understand why:

---

Firstly, I cannot do anything about what servers owners do. I understand you contacted me because I'm the only other "authority" figure that could help you, so I won't hold that against you.
That said, you'd be surprised how many server owners do not listen to me or take my advice. :/

Now, you mention instant respawns, and sadly, Lilac doesn't check for Aimlock on players who spawn/respawn... **HOWEVER**, you also mention "teleports". Now, Lilac ignores players who take teleports (buildings from engineers), but it wasn't until version 1.7.0 Beta that Lilac added map teleports to that list.

And the map you got banned on does have map teleports!
Now, I'm going to assume that the server in question is using version 1.6.x of Lilac (or earlier), which doesn't have that map-teleport check.

Looking at this map, there are three-ish map teleports (for each team), and two of them are what's likely causing the issue:
1. "Sniper Duel, Gate 1".
2. "Respawn" (In the sniper duel room, NOT the actual spawn room).

When you take these two, you can in some cases teleport to a spot where you'll be looking straight at an enemy.
**This could cause a false positive.**
Now in Lilac, to get an Aimlock detection, you have to constantly teleport like this to trigger a false positive.
However, it's not impossible.

---

So in case my answer wasn't clear: Yes, you might have gotten false banned, due to map teleports.
You can link the server owners to this reply:  (This link takes you to this comment).

And as for the server owners: Version 1.7.0 is currently in Beta and has a fix for this particular issue. If you still wish to not update yet, you can just set the ConVar `lilac_aimlock 0`.

**Comment by CloudGirlS** [comment] 2021-03-30 08:57
Hello, Owner for lilac. 

So i am Manager of the server orange.  I looked at the logs for this player. Here I send

2021/03/23 17:39:53 [Version 1.6.2] {Name: "الألعاب الحلال" | SteamID: STEAM_0:1:61223317 | IP: } is suspected of using an aimlock (Detection: 2).
2021/03/23 17:40:33 [Version 1.6.2] {Name: "الألعاب الحلال" | SteamID: STEAM_0:1:61223317 | IP: } is suspected of using an aimlock (Detection: 3).
2021/03/23 17:42:03 [Version 1.6.2] {Name: "الألعاب الحلال" | SteamID: STEAM_0:1:61223317 | IP: } is suspected of using an aimlock (Detection: 4).
2021/03/23 17:43:37 [Version 1.6.2] {Name: "الألعاب الحلال" | SteamID: STEAM_0:1:61223317 | IP: } is suspected of using an aimlock (Detection: 5).
2021/03/23 17:43:37 [Version 1.6.2] {Name: "الألعاب الحلال" | SteamID: STEAM_0:1:61223317 | IP: } was banned for Aimlock.

I post the log with no ip for to preserve information.

Have a nice day !  :) Monika

**Comment by J-Tanzanite** [comment] 2021-03-31 10:53
Hi, you can unban this player, as it's likely a false positive due to the map teleports as described above.
I recommend setting "lilac_aimlock" to "0" on this map.

Version 1.7.0 has a fix for this, so on version 1.7.0 you can use "lilac_aimlock 1".

---

Also, I recommend setting "lilac_log_extra" to "2", makes it easier to find false positives.
Thanks for not sharing IP btw :+1:

**Comment by J-Tanzanite** [comment] 2021-04-10 12:38
I am going to close this, as no further replies have been made.
And since this issue has been fixed in the latest version that will be released soon (And is already available as a BETA and can be used).

**Closed by J-Tanzanite** 2021-04-10 12:38 UTC
Labels: Fixed in later version
