### ISSUE TITLE
lilac 1.7.4 Exception reported: Translation failed: invalid client index

### ISSUE THREAD

**Issue by mrdiega** [J-Tanzanite/Little-Anti-Cheat#172] opened 2023-03-31 14:39 UTC
```
L 03/31/2023 - 11:24:34: SourceMod error session started
L 03/31/2023 - 11:24:34: Info (map "$2000$") (file "/home/server2000css/steamcmd/server/cstrike/addons/sourcemod/logs/errors_20230331.log")
L 03/31/2023 - 11:24:34: [SM] Exception reported: Translation failed: invalid client index 1601069410 (arg 6)
L 03/31/2023 - 11:24:34: [SM] Blaming: lilac.smx
L 03/31/2023 - 11:24:34: [SM] Call stack trace:
L 03/31/2023 - 11:24:34: [SM]   [0] Format
L 03/31/2023 - 11:24:34: [SM]   [1] Line 259, lilac\lilac_stock.sp::lilac_ban_client
L 03/31/2023 - 11:24:34: [SM]   [2] Line 369, lilac\lilac_aimbot.sp::lilac_detected_aimbot
L 03/31/2023 - 11:24:34: [SM]   [3] Line 310, lilac\lilac_aimbot.sp::timer_check_aimbot
L 03/31/2023 - 11:41:51: [SM] Exception reported: Translation failed: invalid client index 1601069410 (arg 6)
L 03/31/2023 - 11:41:51: [SM] Blaming: lilac.smx
L 03/31/2023 - 11:41:51: [SM] Call stack trace:
L 03/31/2023 - 11:41:51: [SM]   [0] Format
L 03/31/2023 - 11:41:51: [SM]   [1] Line 259, lilac\lilac_stock.sp::lilac_ban_client
L 03/31/2023 - 11:41:51: [SM]   [2] Line 369, lilac\lilac_aimbot.sp::lilac_detected_aimbot
L 03/31/2023 - 11:41:51: [SM]   [3] Line 310, lilac\lilac_aimbot.sp::timer_check_aimbot
L 03/31/2023 - 12:03:39: [SM] Exception reported: Translation failed: invalid client index 1601069410 (arg 6)
L 03/31/2023 - 12:03:39: [SM] Blaming: lilac.smx
L 03/31/2023 - 12:03:39: [SM] Call stack trace:
L 03/31/2023 - 12:03:39: [SM]   [0] Format
L 03/31/2023 - 12:03:39: [SM]   [1] Line 259, lilac\lilac_stock.sp::lilac_ban_client
L 03/31/2023 - 12:03:39: [SM]   [2] Line 369, lilac\lilac_aimbot.sp::lilac_detected_aimbot
L 03/31/2023 - 12:03:39: [SM]   [3] Line 310, lilac\lilac_aimbot.sp::timer_check_aimbot
L 03/31/2023 - 12:12:24: [SM] Exception reported: Translation failed: invalid client index 1601069410 (arg 6)
L 03/31/2023 - 12:12:24: [SM] Blaming: lilac.smx
L 03/31/2023 - 12:12:24: [SM] Call stack trace:
L 03/31/2023 - 12:12:24: [SM]   [0] Format
L 03/31/2023 - 12:12:24: [SM]   [1] Line 259, lilac\lilac_stock.sp::lilac_ban_client
L 03/31/2023 - 12:12:24: [SM]   [2] Line 369, lilac\lilac_aimbot.sp::lilac_detected_aimbot
L 03/31/2023 - 12:12:24: [SM]   [3] Line 310, lilac\lilac_aimbot.sp::timer_check_aimbot
L 03/31/2023 - 13:46:56: [SM] Exception reported: Translation failed: invalid client index 1601069410 (arg 6)
L 03/31/2023 - 13:46:56: [SM] Blaming: lilac.smx
L 03/31/2023 - 13:46:56: [SM] Call stack trace:
L 03/31/2023 - 13:46:56: [SM]   [0] Format
L 03/31/2023 - 13:46:56: [SM]   [1] Line 259, lilac\lilac_stock.sp::lilac_ban_client
L 03/31/2023 - 13:46:56: [SM]   [2] Line 369, lilac\lilac_aimbot.sp::lilac_detected_aimbot
L 03/31/2023 - 13:46:56: [SM]   [3] Line 310, lilac\lilac_aimbot.sp::timer_check_aimbot
L 03/31/2023 - 14:26:59: Error log file session closed.
```
i have 100% latest translations
For clarity, I am attaching my files
https://disk.yandex.ru/d/7AX90jPHy4DBxQ

css:ob
sm 1.11
[Lilac] Little Anti-Cheat" (1.7.4) by J_Tanzanite

lilac_aimbot "5"
lilac_angles "0"
lilac_angles_patch "0"

**Comment by mrdiega** [comment] 2023-04-01 11:46
The plugin detects cheaters well in cs:s, but does not ban

```
01/04/2023 14:28:57 [Version 1.7.4] {Name: "c4u" | SteamID: STEAM_0:0:1257711924 | IP: 217.107.199.121} is suspected of using an aimbot (Detection: 2 | Delta: 7 | TotalDelta: 81 | Detected: Aim-Snap2 Autoshoot Angle-Repeat).
01/04/2023 14:30:59 [Version 1.7.4] {Name: "c4u" | SteamID: STEAM_0:0:1257711924 | IP: 217.107.199.121} is suspected of using an aimbot (Detection: 3 | Delta: 2 | TotalDelta: 14 | Detected: Autoshoot Angle-Repeat).
01/04/2023 14:31:03 [Version 1.7.4] {Name: "c4u" | SteamID: STEAM_0:0:1257711924 | IP: 217.107.199.121} is suspected of using an aimbot (Detection: 4 | Delta: 2 | TotalDelta: 14 | Detected: Autoshoot Angle-Repeat).
01/04/2023 14:31:18 [Version 1.7.4] {Name: "c4u" | SteamID: STEAM_0:0:1257711924 | IP: 217.107.199.121} is suspected of using an aimbot (Detection: 5 | Delta: 1 | TotalDelta: 13 | Detected: Autoshoot Angle-Repeat).
01/04/2023 14:31:18 [Version 1.7.4] {Name: "c4u" | SteamID: STEAM_0:0:1257711924 | IP: 217.107.199.121} was banned for Aimbot.
```

In the logs it says that the cheater is banned, but in fact he remains on the server and an error appears that I showed. Look at the time in the logs
```
L 04/01/2023 - 14:31:18: SourceMod error session started
L 04/01/2023 - 14:31:18: Info (map "$2000$") (file "/home/server2000css/steamcmd/server/cstrike/addons/sourcemod/logs/errors_20230401.log")
L 04/01/2023 - 14:31:18: [SM] Exception reported: Translation failed: invalid client index 1601069410 (arg 6)
L 04/01/2023 - 14:31:18: [SM] Blaming: lilac.smx
L 04/01/2023 - 14:31:18: [SM] Call stack trace:
L 04/01/2023 - 14:31:18: [SM]   [0] Format
L 04/01/2023 - 14:31:18: [SM]   [1] Line 259, lilac\lilac_stock.sp::lilac_ban_client
L 04/01/2023 - 14:31:18: [SM]   [2] Line 369, lilac\lilac_aimbot.sp::lilac_detected_aimbot
L 04/01/2023 - 14:31:18: [SM]   [3] Line 310, lilac\lilac_aimbot.sp::timer_check_aimbot
```

**Comment by J-Tanzanite** [comment] 2023-04-01 13:17
> css:ob

Is that a cracked version of CS? Because it's not supported.
I'll still try to support you, just have no clue what game that is.

You're not the only person who gets that particular error, it's a fairly rare one, seems common on cracked versions of CS:S...

What your `lilac_ban_language` ConVar is set to?

**Comment by mrdiega** [comment] 2023-04-01 13:48
> > css:ob
> 
> Is that a cracked version of CS? Because it's not supported. I'll still try to support you, just have no clue what game that is.
> 
> You're not the only person who gets that particular error, it's a fairly rare one, seems common on cracked versions of CS:S...
> 
> What your `lilac_ban_language` ConVar is set to?

css:ob it is steam version (v92)

"lilac_ban_language" = "1"
[https://ibb.co/qN683md](url)

**Comment by J-Tanzanite** [comment] 2023-04-01 13:56
Alright, try setting it to 0 in your config, and see if that fixes it.

**Comment by mrdiega** [comment] 2023-04-02 15:14
```
02/04/2023 18:01:41 [Version 1.7.4] {Name: "ИСУС777" | SteamID: STEAM_0:0:1977928745 | IP: 80.76.61.83} is suspected of using an aimlock (Detection: 2).
02/04/2023 18:03:47 [Version 1.7.4] {Name: "ИСУС777" | SteamID: STEAM_0:0:1977928745 | IP: 80.76.61.83} is suspected of using an aimlock (Detection: 3).
02/04/2023 18:03:58 [Version 1.7.4] {Name: "ИСУС777" | SteamID: STEAM_0:0:1977928745 | IP: 80.76.61.83} is suspected of using an aimlock (Detection: 4).
02/04/2023 18:06:09 [Version 1.7.4] {Name: "ИСУС777" | SteamID: STEAM_0:0:1977928745 | IP: 80.76.61.83} is suspected of using an aimlock (Detection: 5).
02/04/2023 18:06:42 [Version 1.7.4] {Name: "ИСУС777" | SteamID: STEAM_0:0:1977928745 | IP: 80.76.61.83} is suspected of using an aimlock (Detection: 6).
```
New problem. After 5 detections, nothing happens. The cheater does not get banned.
"lilac_ban_language" = "0"
There are no errors in the logs.

**Comment by J-Tanzanite** [comment] 2023-04-24 13:40
Any updates on whether this fixed your issue or not?

**Comment by J-Tanzanite** [comment] 2023-05-24 14:45
As far as I can tell, there's nothing different in version 1.7.3 and 1.7.4 that could possibly cause this issue, or have resolved it.
And it appears to be an issue with translations only?

Given how I've never gotten this issue, and reports about this are fairly rare, I don't know how I would even begin to nail down where the issue is.
Adding a 'BUG' label to this, as it's clearly a bug, but one I can't seem to recreate.

**Comment by azalty** [comment] 2023-05-25 06:55
@freakexeuLow do you use normal csgo or a cracked / modified version?

**Comment by sapphonie** [comment] 2023-11-14 05:42
Need more info. Until then, closing

**Closed by sapphonie** 2023-11-14 05:42 UTC
Labels: Bug
