### ISSUE TITLE
Reproducible false postive bunnyhop detection (Legit)

### ISSUE THREAD

**Issue by m4rkey** [J-Tanzanite/Little-Anti-Cheat#18] opened 2020-05-29 08:20 UTC
Hi, I am reporting a reproducible false positive, that happens on 64 tick servers, on both settings (1/2) for legit players. I had one of my players who bunnyhops via the space bar, and he was able to consistently hit 5 hops and get himself banned, and then by switching the detection method  consistently hit 10 in a row resulting in a ban.

This itself should cause for some concern and by default it should not perma-ban in my opinion, instead it should log to file, This might be something worth looking into, I am aware of the setting the ban length via a command, but for newcomers to the anti-cheat I don't believe this is the best option.

Note: I am not trying to start any un-necessary drama as I read your posts about it, but this does raise some concern. (I am also using my branch of MySQL logging thats why it reads RC3 for 1.5.0)

Here is a video as an example of one of my legit players doing this: https://www.youtube.com/watch?v=esq-sgref6U&feature=youtu.be

**Comment by J-Tanzanite** [comment] 2020-05-29 09:25
How does this raise a concern if you've read my posts about it?

For any newcommers to this thread/issue, I recommend reading what I've said here: https://forums.alliedmods.net/showpost.php?p=2701978&postcount=110

People have added me and PM'ed me over this issue before, and I've had to repeat myself many times. So it's not a problem that you bring it up here, as eventually someone would ask the same.
Tho I'm starting to consider making an article about this and just linking people to it, as repeating myself is tiresome :P

Also, you did not give any reproducible steps, saying *"I pressed jump at the exact time I hit the ground"* isn't reproducible, watch this video:
https://www.youtube.com/watch?v=VBUPlhiki3s

To those who just wanna know if this is possible: https://youtu.be/VBUPlhiki3s?t=355
And: https://youtu.be/wJBTEvYZFP8?t=175

Fact of the matter is, getting a false positive for Bhop requires that you get consecutive perfect bhops several times in a row. And if you stand on the ground without jumping for a single tick - then the Bhop detection counter resets. So the Bhops **HAVE** to be perfect.
If you spam jump, say with a macro or scrollwheel, then it will only ban on the 10th perfect consecutive Bhop.
And the chance of a false positive happening there is 0.01 to 0.1% chance.

As for your chance of getting a false positive for 5 Bhops: If we assume a 50% chance of landing a perfect bhop: (0.5^5)*100 = 3.125% chance.
But, that's assuming a 50% chance, which is absolute bunkers, more likely, you have a 30% chance, in which case, the chance of a false positive is: (0.3^5)*100 = 0.243% chance.

In short, your player is lying.
It isn't impossible to get a false positive for Bhop, but like I said to freak.exe_uLow: *"Bhop detections are always about statistics, and there isn't any way around that. Some cheat detections features cannot be done as legit, and thus, are almost always guarantied to be accurate. Others like Bhop, is drawing a line in the sand as to where the likelihood of being legit ends."*

You claim he managed to get false banned several times in a row, had it only been one time or a loooong time between each attempt - then sure, he's very **lucky**.
But several times in a row? No, he is lying.

Faking footage of Bhop is also easy to do, as there is already a command you can use in CS:GO that will auto jump for you. Hence why a video doesn't make a claim more credible in this situation.

There is one last thing that needs to be said.
The chance of a false positive for Bhop can be 0.01% ~ 0.2%, but that doesn't mean there is a 0.01% ~0.2% chance of legit players getting false banned; these two things are not the same thing.
One counts players attempting to Bhop, and the other counts **ALL** players, even those who don't even try to Bhop.

Most people who play legit, don't even attempt to Bhop, so the concern that legit players might get false banned is... Well... Not a concern.

**Comment by m4rkey** [comment] 2020-05-29 09:30
I litterally watched him do it multiple times, and get himself banned multiple times. but if you claim thats the case. I will move on from this, as its clear that this wont change the direction.

**Comment by J-Tanzanite** [comment] 2020-05-29 10:28
First off, I wanna apologize for being dismissive and for calling your friend a liar.
I've been sleep deprived for days now, and I've been in a poor mood for days as well. That doesn't excuse my behavior, but that does mean I'm not thinking, and merely reacting. 

I want some clarification, if I may.

Your friend managed to land 5 bhops, with 5 spacebar presses, 4 times in a row?
As in, after you unbanned him, he did it again on his first try? Every time?

And on the 10th bhop test, he managed to get false banned twice in a row, without failure?
This clarification is important.

**Comment by m4rkey** [comment] 2020-05-29 10:35
After, I unbanned my friend, he would go back into the server, and try to make it go off again it wouldnt be exactly the first time, he would mess up and keep trying until he got it to trigger, and then after he kept doing that, I unbanned him again after the 4th time, and switched the detection method to do the 10 hop version, in which that took him a little longer to false postive, but he got it on his second or third try. (Not twice, I thought it was twice, it was only once, the other one was the 5 hop version Apologies.) Hes no stellar bunnyhopper, but all he is doing is pressing his spacebar to bunnyhop like he normally does.

**Comment by J-Tanzanite** [comment] 2020-05-29 10:55
Not consecutive false bans then (as in, he tried but failed, but eventually got false banned).

Assuming what you are saying is true, which I will assume, then there would be an issue.
As the logs show, he isn't spamming jump, meaning he is timing each jump.

Which leaves us with a few possible options:
1. Timing your jumps is easier than I thought (more than 40%, maybe even higher than 50%).
2. I'm right and he just is unlucky.
3. Your friend is cheating; Which you doubt, and we are assuming he isn't cheating.

If it's the first one, then the ban length of Bhop should be, as you suggest, be lowered.
If it's the second one, then lowering the ban length should be __considered__.
And If it's the third, then no changes will be made.
...

I wanna see your friend do this.
I want to setup a CS:GO server and look at this myself.
Would your friend be willing to participate in this test?

**Comment by m4rkey** [comment] 2020-05-29 11:48
Yes he would. He can replicate it on 64 tick, if you setup a server and setup a time we can do this. It seems you are from Sweden or around there so times might be a bit different for us.

**Comment by J-Tanzanite** [comment] 2020-05-29 12:14
Norway, in Scandinavia, there are jokes about each other, so I joke about being from Sweden. But neighboring country, so not far off.

Which country does your friend live in?
You can give a close country/place if that is more comfortable; just so I know where to setup the server.

Current options are:
1. UK / England
2. Netherlands.
3. Germany.
4. Canada.
5. US - New York.
6. US - Washington.
7. US - Georgia.
8. US - Arizona

**Comment by m4rkey** [comment] 2020-05-29 17:39
Arizona would be the closest.

**Comment by J-Tanzanite** [comment] 2020-05-30 18:27
I found the problem.
I wrote a test for your friend, tried it out myself, and noticed where the issue lies.
I made a simple mistake.

---

What I said about the chances of false positives in regards to scrollwheel and macros is correct however.
The chance of a false positive for 10 bhops with spam is: 0.01 to 0.1%.
The chance of a false positive for 5 bhops with spam is: ... Not measurable, as it would skip to only banning on 10 bhops on spam.

I assumed the chance of landing a perfect bhop by manually pressing space to be around 30%.
It's higher for some people, like myself as it turns out.
It's around 50% by manually timing it on a flat surface.

---

There is a way to fix this, I already measure how many times someone presses the jump button, as to check for spam, so that I can prevent banning on 5 bhops if the player is using a macro or their scrollwheel.
However, if I were to change that to count how many ticks you are holding down your +jump key, then that would greatly decrease the chance of a false positive.
Legit players when they press their jump key (spacebar), will hold it down for about 5-10 ticks, rarely will it go below 3 ticks.
Cheats on the other hand, will usually only press the jump key once or twice (SMAC Bypass) for exactly one tick.

If someone where to use a Macro or scrollwheel, then that wouldn't change much, as the ticks where +jump is held down would be aprox the same as counting jump presses.

So, if I were to change this:
``` c
	if (icvar[CVAR_BHOP] && !cvar_bhop_value) {
		int flags = GetEntityFlags(client);
		if ((buttons & IN_JUMP) && !(lbuttons[client] & IN_JUMP)) {
			if ((flags & FL_ONGROUND)) {
				lilac_detected_bhop(client);

				playerinfo_bhop[client]++;
			}

			playerinfo_jumps[client]++;
		}
		else if ((flags & FL_ONGROUND)) {
			playerinfo_bhop[client] = 0;
			playerinfo_jumps[client] = 0;
		}
	}
```
To:
``` c
	if ((buttons & IN_JUMP))
		playerinfo_jumps[client]++;

	if (icvar[CVAR_BHOP] && !cvar_bhop_value) {
		int flags = GetEntityFlags(client);
		if ((buttons & IN_JUMP) && !(lbuttons[client] & IN_JUMP)) {
			if ((flags & FL_ONGROUND)) {
				lilac_detected_bhop(client);

				playerinfo_bhop[client]++;
			}
		}
		else if ((flags & FL_ONGROUND)) {
			playerinfo_bhop[client] = 0;
			playerinfo_jumps[client] = 0;
		}
	}
```

Then the chances of getting false bans would drop significantly.
With spam Macro/Scrollwheel: 0.01 to 0.1%.
Manually timing: 0.1 to 0.5%.

---

And I think you are right, perma banning by default for something that can happen to 0.5% of players is too high, it should instead default to banning for a week or so, not permanently.

---

So, how many false bans have there been for Bhop?
I'd say, 5% of all Bhop bans from Lilac are false positives.
And there is currently no way of telling which is legit and which is from cheats.

**Comment by m4rkey** [comment] 2020-05-31 03:46
So is this what we are switching to?

**Comment by J-Tanzanite** [comment] 2020-05-31 11:28
Pretty much.

I still find it strange, as a few months ago, a Korean dude had his friend banned on someone else's server. And he asked me to fix it, I told him there wasn't a problem and he insisted that I try to get myself banned...

So I did, and after 30 minutes of trying to get myself banned, I gave up, couldn't do it.
Hence why I assumed the chance of landing a perfect bhop manually was about 30%, which seemed about right.
(0.3^5)\*100 = 0.24%

However, yesterday I managed to do nearly 40%... Which: (0.4^5)\*100 = 1%
It's not a far stretch to imagine that some people might be able to do 50% if I hit 40%...
So: (0.5^5)\*100 = 3.1%

I actually assume around 2% of all 5 bhop bans are false positives, but I'm rounding it up to 5%, just in-case.
Either way, a 1% chance of a false ban is too high to justify a perma ban by default.
Heck, even the original estimate of 0.2% chance of a false positive ban don't justify a perma ban by default.

---

After I add this patch to version 1.6.0, then the chance of a false positive will drop to 0.1 to 0.5%
Which I still don't feel justifies a perma ban by default, only a week.

And with this patch, getting banned for 5 bhops requires that you hold your jump key down for extremely few ticks per jump, so almost guarantied to be cheating at that point.

**Comment by J-Tanzanite** [comment] 2020-05-31 17:35
In version 1.6.0, I am going to credit you for the patch, would your friend be ok with being credited as well? And if so, what alias does he go by?

**Comment by m4rkey** [comment] 2020-06-01 15:02
He goes by the name of Thundy.

**Comment by J-Tanzanite** [comment] 2020-06-02 11:35
Fixed in development branch, will do more testing and then it will be official.

**Closed by J-Tanzanite** 2020-06-02 11:35 UTC
Labels: Bug
