### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by cleber1337** [J-Tanzanite/Little-Anti-Cheat#29] opened 2020-07-26 18:23 UTC
the plugin is banning players who are not cheat, and are not doing anything to detect, simply the
plugin applies the ban

**Comment by J-Tanzanite** [comment] 2020-07-26 18:30
You're going to have to give a little more information :)

What game?
What map?
Lilac Version?
What were they banned for?

And detection logs, if possible (with IPs removed).

**Comment by cleber1337** [comment] 2020-07-26 18:32
Game: CSGO
Map: Any map
Lilac Version: 1.6.0
What were they banned for: Aimbot

Logs:

![image](https://user-images.githubusercontent.com/64625663/88486606-3c5b2f00-cf55-11ea-8063-857005b9cacd.png)

**Comment by J-Tanzanite** [comment] 2020-07-26 18:59
Clearly this player is doing something, I thought when you said "and are not doing anything to detect" that they were just joining the server and standing still and getting banned. But no, he is killing other players.

Autoshoot detections is when a player is doing 1Tick perfect shots when killing other players, however Lilac doesn't detect autoshoot unless a player gets 2 1Tick perfect shots in a row (or something else is detected along side autoshoot).

Autoshoot detections is what you often end up seeing on legit cheaters (cheaters who try to look legit). You can get detected for Autoshoot while rage hacking as well, but that's less common.

Unless this player is using scroll to shoot, the ban is valid and he was cheating.

You can see my previous posts about Autoshoot here:
https://forums.alliedmods.net/showpost.php?p=2700063&postcount=95
https://forums.alliedmods.net/showpost.php?p=2699215&postcount=82
https://github.com/J-Tanzanite/Little-Anti-Cheat/issues/6


Either way, not a bug.

**Comment by J-Tanzanite** [comment] 2020-07-30 07:16
Due to lack of replies, I am going to close this now.
If you have any other questions, feel free to open an issue :)

**Closed by J-Tanzanite** 2020-07-30 07:16 UTC
