### ISSUE TITLE
Please add support sb/ma

### ISSUE THREAD

**Issue by panikajo** [J-Tanzanite/Little-Anti-Cheat#3] opened 2020-04-29 13:35 UTC
Please add support for ban
This https://github.com/sbpp
and This https://github.com/SB-MaterialAdmin

**Comment by J-Tanzanite** [comment] 2020-04-30 10:49
There is already support for sourcebans++.


As for SB-MaterialAdmin... Seems like a lot of people want me to add support for "SBMA", but the problem is, I have no clue what it is. I've never heard of "SBMA" before.

I tried to look it up, and google gave me a lot of Russian results.
I don't know Russian, but I hope "google translate" does an ok job of translating Russian to English.

So please correct me if I am wrong here. "SB-Material Admin" is a Russian fork/version of Sourcebans++? Is that right?

If that is correct, I'm assuming adding support for "SBMA" would be as easy as changing:\
`#include <sourcebanspp>`\
to: `#include <materialadmin>`

And changing:\
`sourcebans_exist = LibraryExists("sourcebans++");`\
to: `materialadmin_exist = LibraryExists("materialadmin");`

However, what would be the function to call a ban via SB-MateralAdmin?
I read through the source, is this the correct function?

`MABanPlayer(0 /*Server*/, client /*Client to be banned*/, MA_BAN_STEAM /*Ban via SteamID*/, 0 /*Time in minutes, 0 = forever*/, string_reason /*Reason behind the ban*/);`

Cleaner version without comments:\
`MABanPlayer(0, client, MA_BAN_STEAM, 0, string_reason);`

I'm not familiar with SB-MaterialAdmin, since I haven't heard about until now.\
If you can answer these questions, I would **Love** to support "SBMA"

**Comment by CrazyHackGUT** [comment] 2020-05-01 14:05
> "SB-Material Admin" is a Russian fork/version of Sourcebans++? Is that right?

Yes.

>If that is correct, I'm assuming adding support for "SBMA" would be as easy as changing:
`#include <sourcebanspp>`
to: `#include <materialadmin>`

Yes. You can just use `#tryinclude` + `#undef REQUIRE_PLUGIN` for supporting both plugins.

> is this the correct function?

Yes.

**Comment by J-Tanzanite** [comment] 2020-05-01 14:57
Alright, I made a quick update to lilac.sp.
Try and see if this works: https://github.com/J-Tanzanite/Little-Anti-Cheat/blob/master/lilac.sp

If this works fine, then this will become official on AlliedModders as well, and MaterialAdmin will be officially supported.

Also, didn't know "tryinclude" was a thing, thanks for informing me :)

**Comment by J-Tanzanite** [comment] 2020-05-03 11:27
I'm going to consider this issue resolved, and will close it in a few days if no further comments are made.
Like always, leaving it up for a few days, just in case :)

**Comment by KiteKot** [comment] 2020-05-03 21:00
Hello. You can make anti-cheat not detect bhop in VIP players. Because bhop VIP players ban. I will attach Vip_core
https://github.com/R1KO/VIP-Core

**Comment by panikajo** [comment] 2020-05-03 21:16
> Hello. You can make anti-cheat not detect bhop in VIP players. Because bhop VIP players ban. Please do. I will attach Vip_core
> https://github.com/R1KO/VIP-Core

https://hlmod.ru/threads/little-anti-cheat.52493/#post-464217

**Comment by KiteKot** [comment] 2020-05-03 21:28
> > Hello. You can make anti-cheat not detect bhop in VIP players. Because bhop VIP players ban. Please do. I will attach Vip_core
> > https://github.com/R1KO/VIP-Core
> 
> https://hlmod.ru/threads/little-anti-cheat.52493/#post-464217

Thx

**Comment by TonyS95** [comment] 2020-05-03 23:56
Could you make use of the updater plugin so this auto updates so dont have to check git repo :S

**Comment by J-Tanzanite** [comment] 2020-05-07 19:25
No further comments have been made about MaterialAdmin or Sourcebans++, and seems like other people have got it working fine. So going to consider this issue resolved, as MA and SBPP are both supported now and working.

**Closed by J-Tanzanite** 2020-05-07 19:25 UTC
Labels: Request

**Comment by lucky84** [comment] 2020-05-20 09:55
sry for my question, but support your plugin SourceBans 1.4.11?

**Comment by J-Tanzanite** [comment] 2020-05-20 15:08
Little Anti-Cheat will suport SourceBans++, but SourceBans (Not the new one) will not be supported.

**Comment by lucky84** [comment] 2020-05-21 11:30
ok, thanks for the info

**Comment by fast-kill** [comment] 2020-05-21 12:11
> Небольшой Anti-Cheat будет поддерживать SourceBans ++, но SourceBans (не новый) не будет поддерживаться.

Thank you for this plugin! It works great, I wanted to ask you to develop it more, do more for cs go since it doesn’t detect most cheats, make it ban the twists and aimbots, and even ban transparent walls so that it doesn't let you see through the walls! the author may improve it and modify something for CS GO?, !!!!

**Comment by fast-kill** [comment] 2020-05-21 12:18
> Little Anti-Cheat will suport SourceBans++, but SourceBans (Not the new one) will not be supported.

Thank you for this plugin! It works great, I wanted to ask you to develop it more, do more for cs go since it doesn’t detect most cheats, make it ban the twists and aimbots, and even ban transparent walls so that it doesn't let you see through the walls! the author may improve it and modify something for CS GO?!

**Comment by J-Tanzanite** [comment] 2020-05-21 23:52
Thank you, fast-kill :)
Happy to hear that Little Anti-Cheat is working great for you!

CS:GO isn't a game I play, but it seems like most people who use Little Anti-Cheat use it for CS:GO, so I'll look more into CS:GO cheats soon.
By "twists" I assume you mean Yaw Anti-Aim / Desync, and sure, I'll look into adding support for Desync detection in the future (But nor right now).

Currently, I wanna update stability and performance for Little Anti-Cheat, before adding more cheat detections. So new cheat detection methods won't be added right away, and it may take a while before I do add some new stuff. But I'll look into it in the future.

When it comes to Anti-Wallhacks, I did write an Anti-Wallhack plugin years ago, but have since lost the source files.
However, I'll look into making an unofficial Anti-Wallback **BETA** Plugin that you and others can test out in the future. Please note tho, that currently I am busy with other things, but I will look into maybe writing a BETA Anti-Wallhack plugin :)
Maybe in a month or two.

**Comment by fast-kill** [comment] 2020-05-29 09:09
> Thank you, fast-kill :)
> Happy to hear that Little Anti-Cheat is working great for you!
> 
> CS:GO isn't a game I play, but it seems like most people who use Little Anti-Cheat use it for CS:GO, so I'll look more into CS:GO cheats soon.
> By "twists" I assume you mean Yaw Anti-Aim / Desync, and sure, I'll look into adding support for Desync detection in the future (But not right now).
> 
> Currently, I wanna update stability and performance for Little Anti-Cheat, before adding more cheat detections. So new cheat detection methods won't be added right away, and it may take a while before I do add some new stuff. But I'll look into it in the future.
> 
> When it comes to Anti-Wallhacks, I did write an Anti-Wallhack plugin years ago, but have since lost the source files.
> However, I'll look into making an unofficial Anti-Wallback **BETA** Plugin that you and others can test out in the future. Please note tho, that currently I am busy with other things, but I will look into maybe writing a BETA Anti-Wallhack plugin :)
> Maybe in a month or two.


Thank you, I would be happy to try the beta version.
